"""Coffee and Tank table

Revision ID: 8d3935acd1e9
Revises: 
Create Date: 2018-12-16 23:49:23.895975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3935acd1e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('coffee', sa.Integer(), nullable=True),
    sa.Column('milk', sa.Integer(), nullable=True),
    sa.Column('water', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coffee_name'), 'coffee', ['name'], unique=True)
    op.create_table('tank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('current_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tank_name'), 'tank', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tank_name'), table_name='tank')
    op.drop_table('tank')
    op.drop_index(op.f('ix_coffee_name'), table_name='coffee')
    op.drop_table('coffee')
    # ### end Alembic commands ###
